// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID              int32          `json:"id"`
	PatientUsername string         `json:"patient_username"`
	MedicineID      int32          `json:"medicine_id"`
	Quantity        int32          `json:"quantity"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Doctor struct {
	Username           string           `json:"username"`
	FullName           string           `json:"full_name"`
	MobileNumber       string           `json:"mobile_number"`
	Gender             string           `json:"gender"`
	Age                int32            `json:"age"`
	Specialization     string           `json:"specialization"`
	Email              string           `json:"email"`
	Password           string           `json:"password"`
	RegistrationNumber string           `json:"registration_number"`
	HospitalName       pgtype.Text      `json:"hospital_name"`
	YearsExperience    int32            `json:"years_experience"`
	PasswordChangedAt  pgtype.Timestamp `json:"password_changed_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Medicine struct {
	ID             int32            `json:"id"`
	Name           string           `json:"name"`
	Description    string           `json:"description"`
	ExpiryDate     pgtype.Date      `json:"expiry_date"`
	Quantity       int32            `json:"quantity"`
	Price          pgtype.Numeric   `json:"price"`
	Discount       int32            `json:"discount"`
	SellerUsername string           `json:"seller_username"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Patient struct {
	Username          string           `json:"username"`
	FullName          string           `json:"full_name"`
	Email             string           `json:"email"`
	MobileNumber      string           `json:"mobile_number"`
	Password          string           `json:"password"`
	Gender            string           `json:"gender"`
	Age               int32            `json:"age"`
	Address           string           `json:"address"`
	EmergencyContact  string           `json:"emergency_contact"`
	PasswordChangedAt pgtype.Timestamp `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type PatientProfile struct {
	ID                 int32            `json:"id"`
	Username           string           `json:"username"`
	DiseaseAllergies   pgtype.Text      `json:"disease_allergies"`
	BloodGroup         pgtype.Text      `json:"blood_group"`
	PrescribedMedicine pgtype.Text      `json:"prescribed_medicine"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Payment struct {
	ID              int32              `json:"id"`
	OrderID         pgtype.Int4        `json:"order_id"`
	UserID          string             `json:"user_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	Status          string             `json:"status"`
	PaymentMethod   string             `json:"payment_method"`
	PaymentIntentID pgtype.Text        `json:"payment_intent_id"`
	ChargeID        pgtype.Text        `json:"charge_id"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PaymentMethod struct {
	ID              int32              `json:"id"`
	UserID          string             `json:"user_id"`
	PaymentMethodID string             `json:"payment_method_id"`
	Type            string             `json:"type"`
	CardLast4       pgtype.Text        `json:"card_last4"`
	CardBrand       pgtype.Text        `json:"card_brand"`
	CardExpMonth    pgtype.Int4        `json:"card_exp_month"`
	CardExpYear     pgtype.Int4        `json:"card_exp_year"`
	IsDefault       pgtype.Bool        `json:"is_default"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Seller struct {
	Username          string           `json:"username"`
	FullName          string           `json:"full_name"`
	Email             string           `json:"email"`
	Password          string           `json:"password"`
	MobileNumber      string           `json:"mobile_number"`
	StoreName         string           `json:"store_name"`
	GstNumber         string           `json:"gst_number"`
	DrugLicenseNumber string           `json:"drug_license_number"`
	SellerType        string           `json:"seller_type"`
	StoreAddress      string           `json:"store_address"`
	PasswordChangedAt pgtype.Timestamp `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}
