// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) (DoctorProfile, error)
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) (PatientProfile, error)
	CreateSellerProfile(ctx context.Context, arg CreateSellerProfileParams) (SellerProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDoctorProfile(ctx context.Context, username string) (string, error)
	DeletePatientProfile(ctx context.Context, username string) (string, error)
	DeleteSellerProfile(ctx context.Context, username string) (string, error)
	DeleteUser(ctx context.Context, username string) error
	FindDoctorsByName(ctx context.Context, arg FindDoctorsByNameParams) ([]FindDoctorsByNameRow, error)
	GetPatientProfile(ctx context.Context, username string) (PatientProfile, error)
	GetSellerProfile(ctx context.Context, shopName string) (SellerProfile, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListDoctorsBySpecialization(ctx context.Context, specialization string) ([]DoctorProfile, error)
	UpdateDoctorProfile(ctx context.Context, arg UpdateDoctorProfileParams) (DoctorProfile, error)
	UpdatePatientProfile(ctx context.Context, arg UpdatePatientProfileParams) (PatientProfile, error)
	UpdateSellerProfile(ctx context.Context, arg UpdateSellerProfileParams) (SellerProfile, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
