// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error)
	ClearCart(ctx context.Context, patientUsername string) error
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateMedicine(ctx context.Context, arg CreateMedicineParams) (Medicine, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreatePatientProfile(ctx context.Context, arg CreatePatientProfileParams) (PatientProfile, error)
	CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteDoctor(ctx context.Context, username string) (string, error)
	DeleteMedicine(ctx context.Context, id int32) (int32, error)
	DeletePatient(ctx context.Context, username string) (string, error)
	DeletePatientProfile(ctx context.Context, username string) error
	DeleteSeller(ctx context.Context, username string) (string, error)
	GetCartCount(ctx context.Context, patientUsername string) (int64, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (Cart, error)
	GetCartItems(ctx context.Context, patientUsername string) ([]GetCartItemsRow, error)
	GetCartTotal(ctx context.Context, patientUsername string) (interface{}, error)
	GetDoctorByName(ctx context.Context, username string) (Doctor, error)
	GetMedicine(ctx context.Context, id int32) (Medicine, error)
	GetMedicineByName(ctx context.Context, name string) (Medicine, error)
	GetPatientByName(ctx context.Context, username string) (Patient, error)
	GetPatientProfile(ctx context.Context, username string) (PatientProfile, error)
	GetSellerByName(ctx context.Context, username string) (Seller, error)
	ListAllMedicines(ctx context.Context) ([]Medicine, error)
	ListDoctorsBySpecialization(ctx context.Context, arg ListDoctorsBySpecializationParams) ([]Doctor, error)
	ListPatientProfiles(ctx context.Context) ([]PatientProfile, error)
	ListSellerMedicinesByExpiry(ctx context.Context, arg ListSellerMedicinesByExpiryParams) ([]Medicine, error)
	ListSellersByStoreName(ctx context.Context, arg ListSellersByStoreNameParams) ([]Seller, error)
	SearchMedicinesByNameSortedByPrice(ctx context.Context, arg SearchMedicinesByNameSortedByPriceParams) ([]Medicine, error)
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (Cart, error)
	UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error)
	UpdateMedicine(ctx context.Context, arg UpdateMedicineParams) (Medicine, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdatePatientProfile(ctx context.Context, arg UpdatePatientProfileParams) (PatientProfile, error)
	UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error)
}

var _ Querier = (*Queries)(nil)
