// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seller_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSellerProfile = `-- name: CreateSellerProfile :one
INSERT INTO seller_profiles (
    username,
    shop_name,
    license_number,
    shop_address,
    phone_number
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING username, shop_name, license_number, shop_address, phone_number
`

type CreateSellerProfileParams struct {
	Username      string `json:"username"`
	ShopName      string `json:"shop_name"`
	LicenseNumber string `json:"license_number"`
	ShopAddress   string `json:"shop_address"`
	PhoneNumber   string `json:"phone_number"`
}

func (q *Queries) CreateSellerProfile(ctx context.Context, arg CreateSellerProfileParams) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, createSellerProfile,
		arg.Username,
		arg.ShopName,
		arg.LicenseNumber,
		arg.ShopAddress,
		arg.PhoneNumber,
	)
	var i SellerProfile
	err := row.Scan(
		&i.Username,
		&i.ShopName,
		&i.LicenseNumber,
		&i.ShopAddress,
		&i.PhoneNumber,
	)
	return i, err
}

const deleteSellerProfile = `-- name: DeleteSellerProfile :one
DELETE FROM seller_profiles
WHERE username = $1
RETURNING username
`

func (q *Queries) DeleteSellerProfile(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, deleteSellerProfile, username)
	err := row.Scan(&username)
	return username, err
}

const getSellerProfile = `-- name: GetSellerProfile :one
SELECT username, shop_name, license_number, shop_address, phone_number FROM seller_profiles
WHERE shop_name = $1 LIMIT 1
`

func (q *Queries) GetSellerProfile(ctx context.Context, shopName string) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, getSellerProfile, shopName)
	var i SellerProfile
	err := row.Scan(
		&i.Username,
		&i.ShopName,
		&i.LicenseNumber,
		&i.ShopAddress,
		&i.PhoneNumber,
	)
	return i, err
}

const updateSellerProfile = `-- name: UpdateSellerProfile :one
UPDATE seller_profiles
SET
    shop_name = COALESCE($1, shop_name),
    license_number = COALESCE($2, license_number),
    shop_address = COALESCE($3, shop_address),
    phone_number = COALESCE($4, phone_number)
WHERE
    username = $5
RETURNING username, shop_name, license_number, shop_address, phone_number
`

type UpdateSellerProfileParams struct {
	ShopName      pgtype.Text `json:"shop_name"`
	LicenseNumber pgtype.Text `json:"license_number"`
	ShopAddress   pgtype.Text `json:"shop_address"`
	PhoneNumber   pgtype.Text `json:"phone_number"`
	Username      string      `json:"username"`
}

func (q *Queries) UpdateSellerProfile(ctx context.Context, arg UpdateSellerProfileParams) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, updateSellerProfile,
		arg.ShopName,
		arg.LicenseNumber,
		arg.ShopAddress,
		arg.PhoneNumber,
		arg.Username,
	)
	var i SellerProfile
	err := row.Scan(
		&i.Username,
		&i.ShopName,
		&i.LicenseNumber,
		&i.ShopAddress,
		&i.PhoneNumber,
	)
	return i, err
}
